"""Reorder Models

Revision ID: a2f3d49ff72d
Revises: fbf860b97c7d
Create Date: 2018-06-08 12:58:46.655256

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2f3d49ff72d'
down_revision = 'fbf860b97c7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('section_id', sa.Integer(), nullable=False))
    op.drop_constraint('book_section_fkey', 'book', type_='foreignkey')
    op.create_foreign_key(None, 'book', 'section', ['section_id'], ['id'])
    op.drop_column('book', 'section')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('book', sa.Column('section', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'book', type_='foreignkey')
    op.create_foreign_key('book_section_fkey', 'book', 'section', ['section'], ['id'])
    op.drop_column('book', 'section_id')
    # ### end Alembic commands ###
